import IconArrow from '@assets/icons/Arrow';
import IconVideo from '@assets/icons/Video';
import { NavbarType } from '@type/index';

export const navbarList: NavbarType[] = [
    {
        id: 1,
        title: 'video',
        icon: <IconArrow />,
        submenu: {
            header: 'createVideo',
            icon: <IconVideo />,
            headerClass: 'blue',
            hasMoreBtn: true,
            category: {
                title: 'categories',
                items: [
                    { id: 1, title: 'intros' },
                    { id: 2, title: 'animations' },
                    { id: 3, title: 'musicVisualizations' },
                    { id: 4, title: 'videoEditing' },
                    { id: 5, title: 'youtubeVideos' },
                    { id: 6, title: 'slideshows' },
                    { id: 7, title: 'videoPresentations' },
                    { id: 8, title: 'videoInvitations' },
                    { id: 9, title: 'openerAnimations' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
            featured: {
                title: 'featured',
                items: [
                    { id: 1, title: 'animatedExplainers' },
                    { id: 2, title: 'youtubeIntros' },
                    { id: 3, title: 'animatedTexts' },
                    { id: 4, title: 'logoAnimations' },
                    { id: 5, title: 'birthdayGreetings' },
                    { id: 6, title: 'outroAnimation' },
                    { id: 7, title: '2DAnimations' },
                    { id: 8, title: 'animatedECards' },
                    { id: 9, title: 'worldOfVideos' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
        },
    },
    {
        id: 2,
        title: 'website',
        icon: <IconArrow />,
        submenu: {
            header: 'Build Website',
            icon: <IconVideo />,
            headerClass: 'purple',
            hasMoreBtn: true,
            category: {
                title: 'categories',
                items: [
                    { id: 1, title: 'intros' },
                    { id: 2, title: 'animations' },
                    { id: 3, title: 'musicVisualizations' },
                    { id: 4, title: 'videoEditing' },
                    { id: 5, title: 'youtubeVideos' },
                    { id: 6, title: 'slideshows' },
                    { id: 7, title: 'videoPresentations' },
                    { id: 8, title: 'videoInvitations' },
                    { id: 9, title: 'openerAnimations' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
            featured: {
                title: 'featured',
                items: [
                    { id: 1, title: 'animatedExplainers' },
                    { id: 2, title: 'youtubeIntros' },
                    { id: 3, title: 'animatedTexts' },
                    { id: 4, title: 'logoAnimations' },
                    { id: 5, title: 'birthdayGreetings' },
                    { id: 6, title: 'outroAnimation' },
                    { id: 7, title: '2DAnimations' },
                    { id: 8, title: 'animatedECards' },
                    { id: 9, title: 'worldOfVideos' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
        },
    },
    {
        id: 3,
        title: 'logos',
        icon: <IconArrow />,
        submenu: {
            header: 'makeLogos',
            icon: <IconVideo />,
            headerClass: 'yellow',
            hasMoreBtn: true,
            category: {
                title: 'categories',
                items: [
                    { id: 1, title: 'intros' },
                    { id: 2, title: 'animations' },
                    { id: 3, title: 'musicVisualizations' },
                    { id: 4, title: 'videoEditing' },
                    { id: 5, title: 'youtubeVideos' },
                    { id: 6, title: 'slideshows' },
                    { id: 7, title: 'videoPresentations' },
                    { id: 8, title: 'videoInvitations' },
                    { id: 9, title: 'openerAnimations' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
            featured: {
                title: 'featured',
                items: [
                    { id: 1, title: 'animatedExplainers' },
                    { id: 2, title: 'youtubeIntros' },
                    { id: 3, title: 'animatedTexts' },
                    { id: 4, title: 'logoAnimations' },
                    { id: 5, title: 'birthdayGreetings' },
                    { id: 6, title: 'outroAnimation' },
                    { id: 7, title: '2DAnimations' },
                    { id: 8, title: 'animatedECards' },
                    { id: 9, title: 'worldOfVideos' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
        },
    },
    {
        id: 4,
        title: 'mockups',
        icon: <IconArrow />,
        submenu: {
            header: 'generateMockups',
            icon: <IconVideo />,
            headerClass: 'green',
            hasMoreBtn: true,
            category: {
                title: 'categories',
                items: [
                    { id: 1, title: 'intros' },
                    { id: 2, title: 'animations' },
                    { id: 3, title: 'musicVisualizations' },
                    { id: 4, title: 'videoEditing' },
                    { id: 5, title: 'youtubeVideos' },
                    { id: 6, title: 'slideshows' },
                    { id: 7, title: 'videoPresentations' },
                    { id: 8, title: 'videoInvitations' },
                    { id: 9, title: 'openerAnimations' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
            featured: {
                title: 'featured',
                items: [
                    { id: 1, title: 'animatedExplainers' },
                    { id: 2, title: 'youtubeIntros' },
                    { id: 3, title: 'animatedTexts' },
                    { id: 4, title: 'logoAnimations' },
                    { id: 5, title: 'birthdayGreetings' },
                    { id: 6, title: 'outroAnimation' },
                    { id: 7, title: '2DAnimations' },
                    { id: 8, title: 'animatedECards' },
                    { id: 9, title: 'worldOfVideos' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
        },
    },
    {
        id: 5,
        title: 'graphics',
        icon: <IconArrow />,
        submenu: {
            header: 'designGraphics',
            icon: <IconVideo />,
            headerClass: 'rose',
            hasMoreBtn: true,
            category: {
                title: 'categories',
                items: [
                    { id: 1, title: 'intros' },
                    { id: 2, title: 'animations' },
                    { id: 3, title: 'musicVisualizations' },
                    { id: 4, title: 'videoEditing' },
                    { id: 5, title: 'youtubeVideos' },
                    { id: 6, title: 'slideshows' },
                    { id: 7, title: 'videoPresentations' },
                    { id: 8, title: 'videoInvitations' },
                    { id: 9, title: 'openerAnimations' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
            featured: {
                title: 'featured',
                items: [
                    { id: 1, title: 'animatedExplainers' },
                    { id: 2, title: 'youtubeIntros' },
                    { id: 3, title: 'animatedTexts' },
                    { id: 4, title: 'logoAnimations' },
                    { id: 5, title: 'birthdayGreetings' },
                    { id: 6, title: 'outroAnimation' },
                    { id: 7, title: '2DAnimations' },
                    { id: 8, title: 'animatedECards' },
                    { id: 9, title: 'worldOfVideos' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
        },
    },
    {
        id: 6,
        title: 'explore',
        icon: <IconArrow />,
        submenu: {
            header: 'exploreAi',
            icon: <IconVideo />,
            hasMoreBtn: true,
            category: {
                title: 'categories',
                items: [
                    { id: 1, title: 'intros' },
                    { id: 2, title: 'animations' },
                    { id: 3, title: 'musicVisualizations' },
                    { id: 4, title: 'videoEditing' },
                    { id: 5, title: 'youtubeVideos' },
                    { id: 6, title: 'slideshows' },
                    { id: 7, title: 'videoPresentations' },
                    { id: 8, title: 'videoInvitations' },
                    { id: 9, title: 'openerAnimations' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
            featured: {
                title: 'featured',
                items: [
                    { id: 1, title: 'animatedExplainers' },
                    { id: 2, title: 'youtubeIntros' },
                    { id: 3, title: 'animatedTexts' },
                    { id: 4, title: 'logoAnimations' },
                    { id: 5, title: 'birthdayGreetings' },
                    { id: 6, title: 'outroAnimation' },
                    { id: 7, title: '2DAnimations' },
                    { id: 8, title: 'animatedECards' },
                    { id: 9, title: 'worldOfVideos' },
                    { id: 10, title: 'greetingCards' },
                ],
            },
        },
    },
];

export const secondaryNavbarList: NavbarType[] = [
    {
        id: 7,
        title: 'pricing',
    },
    {
        id: 8,
        title: 'learn',
        icon: <IconArrow />,
        isSecondary: true,
        submenu: {
            header: 'blogAndHelp',
            hasMoreBtn: false,
            category: {
                title: 'blog',
                items: [
                    { id: 1, title: 'intros' },
                    { id: 2, title: 'animations' },
                    { id: 3, title: 'musicVisualizations' },
                    { id: 4, title: 'videoEditing' },
                    { id: 5, title: 'youtubeVideos' },
                ],
            },
            featured: {
                title: 'help',
                items: [
                    { id: 1, title: 'animatedExplainers' },
                    { id: 2, title: 'youtubeIntros' },
                    { id: 3, title: 'animatedTexts' },
                    { id: 4, title: 'logoAnimations' },
                    { id: 5, title: 'birthdayGreetings' },
                ],
            },
        },
    },
];
